### PR TITLE
DATAREDIS-729 - ZREVRANGEBYLEX command

### PR DESCRIPTION
**Pull request by anshlykov**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAREDIS).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

This PR adds support for the `ZREVRANGEBYLEX` command from the original [issue](https://jira.spring.io/browse/DATAREDIS-729).

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks a lot. Do you want to add the reactive variants for `ZREVRANGEBYLEX`?

**Comment by anshlykov** [comment]
@mp911de It seems to me that this has already implemented. https://github.com/spring-projects/spring-data-redis/blob/0279c25b504ed9913b30b48dce21aa5f536c83ea/src/main/java/org/springframework/data/redis/connection/ReactiveZSetCommands.java#L1918

**Comment by mp911de** [comment]
You're right, my bad. I just noticed that there's no change to the reactive API in this PR without actually checking the existing code base.

**Review by mp911de — APPROVED** [review]
Great work, going to take this PR from here.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished now.

**Pull request closed without merging**
