### PR TITLE
DATAREDIS-872 - InitialValue is not specified when two threads use the RedisAtomicInteger constructor concurrently, and two threads can cause thread safety issues.

### PR DESCRIPTION
**Pull request by programmeres**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAREDIS).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by programmeres** [comment]
Can someone handle this pull request?

**Comment by mp911de** [comment]
Thank you for contributing. There are a couple of issues to note here first before we can dig into changing code:

* This pull request was constantly updated and we typically skip PR's that are in progress until we see there come no further changes.
* We should discuss the actual issue first, before proposing code changes to figure out whether it's a real issue or just unintended usage.

**Comment by programmeres** [comment]
Thank you very much. I understand, and the code has been changed, will not continue to update!

**Comment by mp911de** [comment]
Care to squash your commits into a single one and force-push the changes on your branch? This makes it easier for us to apply the merge.

**Comment by programmeres** [comment]
what should I do?

**Comment by mp911de** [comment]
Closing without merge in favor of #367.

**Pull request closed without merging**
