### PR TITLE
DATAREDIS-911 -- fix entity save with custom converter

### PR DESCRIPTION
**Pull request by sajibcuet09**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sajibcuet09 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=537)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=537) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sajibcuet09 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=537)!

**Comment by mp911de** [comment]
Care to provide a test that explains the fix?

**Comment by christophstrobl** [comment]
Thank you @sajibcuet09. Merged to main branch.

**Pull request closed without merging**
