### PR TITLE
DATAREDIS-1157 Allow define prefix key using StringRedisSerializer as…

### PR DESCRIPTION
**Pull request by luramarchanjo**
I am using Spring Data Redis with RedisTemplate to save some cache, but I want to set a prefix key.

 
```
RedisTemplate<String, T> redisTemplate = new RedisTemplate<>();
redisTemplate.setKeySerializer(new StringRedisSerializer()); // Set a prefix key
```

### CODE REVIEW

**Comment by larchanjo** [comment]
@mp911de can you review this?

**Comment by larchanjo** [comment]
@pavel-hp can you review this?

**Comment by mp911de** [comment]
We left some comments in DATAREDIS-1157.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by pivotal-issuemaster** [comment]
@luramarchanjo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=534)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=534) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@luramarchanjo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=534)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=534) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Pull request closed without merging**
