### PR TITLE
DATAREDIS-1103 - Support new KEEPTTL option of the SET operation

### PR DESCRIPTION
**Pull request by dengliming**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAREDIS).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks for your pull request. Instead of adding a new method with a different name, we should introduce overloads accepting `keepTtl` as `boolean` option. `KEEPTTL` can be combined with `XX` and `NX` but not `PX`/`EX` options.

Care to update your pull request?

**Comment by dengliming** [comment]
@mp911de Hi~ Do you mean like this?
`Boolean set(byte[] key, byte[] value, Expiration expiration, SetOption option, boolean keepttl);`

**Comment by mp911de** [comment]
Yes, exactly.

**Comment by dengliming** [comment]
@mp911de Got it. Thanks. That was updated.

**Comment by christophstrobl** [comment]
Thank you @dengliming. We changed the original PR a bit and merged it to the main line.
To ensure existing behaviour is not broken or changed, please make sure to run all tests (with the `-DrunLongTests=true` flag) - thanks!

**Pull request closed without merging**
