### PR TITLE
DATAREDIS-992 - '&' instead of '&&'.

### PR DESCRIPTION
**Pull request by shyam-anand**
Bitwise AND was used instead of logical AND.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@shyam-anand Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=454)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=454) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@shyam-anand Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=454)!

**Comment by mp911de** [comment]
Thanks a lot, that's merged now.

**Comment by shyam-anand** [comment]
@mp911de Thanks Mark! Glad to have contributed to a project that I use quite a lot.

**Pull request closed without merging**
