### PR TITLE
DATAREDIS-348 - Switch to mp911de/lettuce 3.0.

### PR DESCRIPTION
**Pull request by christophstrobl**
Pick up mp911de/lettuce including Sentinel support. Cluster support will be treated in another issues.

This PR supersedes #104 and has been opend in order to double check details with the team.
Thanks @mp911de for the hard work!

### CODE REVIEW

**Comment by mp911de** [comment]
*ping*

**Comment by mlaccetti** [comment]
Can't wait to see this hit!

**Comment by mp911de** [comment]
It's hopefully in the [Gosling](https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-Gosling) release train. @christophstrobl @olivergierke any updates?

**Comment by mp911de** [comment]
Many thanks to you.

**Pull request closed without merging**
