### PR TITLE
Duplicate and invalid code

### PR DESCRIPTION
**Pull request by ZeroOrInfinity**
The versions involved: 1.5.x/1.6.x/1.7.x/1.8.x

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAREDIS).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ZeroOrInfinity Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=505)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=505) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by mp911de** [comment]
These branches are no longer maintained so closing this PR without merging it.

**Comment by pivotal-issuemaster** [comment]
@ZeroOrInfinity Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=505)!

**Comment by ZeroOrInfinity** [comment]
Sorry，My branch was deleted.

**Comment by mp911de** [comment]
I meant Spring Data Redis 1.8.x and older.

**Pull request closed without merging**
