### PR TITLE
DATAREDIS-428 - add annotation for redis message queue

### PR DESCRIPTION
**Pull request by 294033186**
Redis publisher/subscription is not very convenient to use, so I provide a comment on RedisListener。
Related ticket: [DATAREDIS-1026](https://jira.spring.io/browse/DATAREDIS-1026)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@294033186 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=469)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=469) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@294033186 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=469)!

**Comment by mp911de** [comment]
Please file a [ticket](https://jira.spring.io/browse/DATAREDIS) in our JIRA and elaborate on what you're trying to achieve first before proposing code changes. See also the [contribution guide](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc) for further details.

**Comment by 294033186** [comment]
> Please file a [ticket](https://jira.spring.io/browse/DATAREDIS) in our JIRA and elaborate on what you're trying to achieve first before proposing code changes. See also the [contribution guide](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc) for further details.
I have submitted the relevant JIRA
https://jira.spring.io/browse/DATAREDIS-1026

**Comment by mp911de** [comment]
See also #1004.

**Comment by mp911de** [comment]
We will have to revisit this topic in a bigger scope instead therefore we're closing this pull request without merge.

**Pull request closed without merging**
