### PR TITLE
DATAREDIS-749 - Upgrade to Jedis 3

### PR DESCRIPTION
**Pull request by gkorland**
Upgrade to Jedis 3

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gkorland Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=374)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=374) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gkorland Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=374)!

**Comment by mp911de** [comment]
Thanks a lot for your pull request. Do you have an ETA for Jedis 3.0 Final? We're good to release a Spring Data Redis milestone with a Jedis milestone for now.

**Comment by gkorland** [comment]
Jedis 3.0 should be released in the next couple of days

**Comment by mp911de** [comment]
Changes in this pull request break a lot of things: Argument conversion, native command invocation, and subsequent tests. Please submit only functional and complete changes, otherwise, we cannot consider a pull request for merging.

Since upgrading to Jedis is long overdue, we will pick up these changes and see how we can fix the broken pieces.

**Comment by gkorland** [comment]
Jedis 3.0.0 was released today

**Comment by mp911de** [comment]
Thanks for the ping. We'll include upgrading to 3.0 GA during the merge.

**Comment by mp911de** [comment]
Merge is blocked by a race condition that fails our tests on a regular basis: https://github.com/xetorthio/jedis/issues/1910. 

Polished code is now [on a feature branch](https://github.com/spring-projects/spring-data-redis/tree/issue/DATAREDIS-749) so we're closing this pull request and we will continue once https://github.com/xetorthio/jedis/issues/1910 is solved.

**Comment by gkorland** [comment]
Fixed released in jedis-3.0.1

**Comment by mp911de** [comment]
Until last week, we were blocked with vacation. We will take another look in the next days.
Am 6. Jan. 2019, 16:26 +0100 schrieb Guy Korland <notifications@github.com>:

**Comment by mp911de** [comment]
That's merged and polished now.

**Comment by gkorland** [comment]
Thanks, when is 2.2.0 planned to be released?

**Comment by gkorland** [comment]
thanks, do you think this issues is related? 
https://github.com/xetorthio/jedis/issues/1933

**Comment by mp911de** [comment]
Please do not resurrect a merged PR for bug report discussions. The linked issue is not valid as it contains an unsupported version usage. Jedis 3 is only supported with Spring Data Redis 2.2, not the 2.1 line.

**Pull request closed without merging**
