### PR TITLE
DATAREDIS-427 - Allow construction of customized JdkSerializationRedisSerializer.

### PR DESCRIPTION
**Pull request by mp911de**
We now allow constructing JdkSerializationRedisSerializer using an own class loader and by specifying custom converters.

Using an own class-loader: `new JdkSerializationRedisSerializer(classLoader)`

Using own serializers: `new JdkSerializationRedisSerializer(new SerializingConverter(), new DeserializingConverter(new DefaultDeserializer(classLoader)))`

----

Related ticket: [DATAREDIS-427](https://jira.spring.io/browse/DATAREDIS-427)

### CODE REVIEW

**Comment by mp911de** [comment]
@rwinch Do you want to take also a look on this?

**Comment by rwinch** [comment]
@mp911de Thanks for sending this for my review! Out of curiosity what is the minimum Spring version that is supported?

**Comment by mp911de** [comment]
@rwinch You require at least 4.2.1 for this particular feature. With the Hopper release train, we require at least 4.2.

**Comment by rwinch** [comment]
@mp911de Ok I just wanted to make sure you were aware the constructor wasn't added till 4.2.1.

+1 from me

**Pull request closed without merging**
