### PR TITLE
Update RedisConnectionUtils.java

### PR DESCRIPTION
**Pull request by miaogr86**
Thank you for proposing a pull request. This template will guide you through the essential steps necessary for a pull request.
Make sure that:

- [ ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAREDIS).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).
- [ ] You provide your full name and an email address registered with your GitHub account. If you’re a first-time submitter, make sure you have completed the [Contributor’s License Agreement form](https://support.springsource.com/spring_committer_signup).

修复 外层没有事务或者只读事务情况下，配置了enableTransactionSupport=true，redis连接没有关闭问题

### CODE REVIEW

**Comment by mp911de** [comment]
Hi, 
could you please tell us about the problem (in English) you're trying to solve by this pull request?

**Comment by miaogr86** [comment]
The outer layer without spring transaction or read-only transactions, RedisTemplate configure enableTransactionSupport=true, redis connection is not closed

**Comment by miaogr86** [comment]
http://blog.oneapm.com/apm-tech/778.html

see chapter ：Spring Data Redis 中的事务陷阱

**Comment by mp911de** [comment]
Thanks for raising this PR. We weren't aware of the issue. We are solving this issue with a slightly different approach, see https://jira.spring.io/browse/DATAREDIS-548, therefore I'm closing this PR.

**Pull request closed without merging**
