### PR TITLE
Improve compatibility with jedis 2.7.1

### PR DESCRIPTION
**Pull request by quaff**
jedis 2.7.1 changed method signature casue spring data redis NPE

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Need to explain why signature changes happen though I didn't participate to implement Jedisque.

First of all, Connection is internal class of Jedis, so we don't recommend outers to use it directly.
We didn't think about reflection, and it's internal class so we think it should be safe.

Jedisque has its command set, so in order to use Jedis from Jedisque, we introduced an interface -  ProtocolCommand which replaces Command so that "command set" could be extended.
In order to let Connection able to send new command set, sendCommand methods signature need to be changed.

**Comment by HeartSaVioR** [comment]
@christophstrobl @thomasdarimont 
Could you take a look at this PR? Or did Spring-data-redis team already take care of it?

**Comment by christophstrobl** [comment]
@HeartSaVioR will have a look. thanks for reminder!

**Comment by HeartSaVioR** [comment]
@christophstrobl 
We found that we're breaking semver (https://github.com/xetorthio/jedis/issues/1043#issuecomment-119036187), and we're discussing about revert the change. 
When we revert and release 2.7.3, spring-data-redis could be safe without applying this PR.
Sorry for annoying and thanks!

**Comment by christophstrobl** [comment]
@HeartSaVioR thanks - yeah I think it's different in the jedis 2.8 branch - will wait and see how things turn out.

**Comment by marcosnils** [comment]
Hi, Jedis 2.7.3 has been just release to fix this issue. Can someone here try and let us knows how it goes?

**Comment by quaff** [comment]
@marcosnils , jedis 2.7.3 works fine, thanks.

**Comment by marcosnils** [comment]
@quaff amazing. @christophstrobl you can go ahead and close this issue :)

**Comment by christophstrobl** [comment]
@marcosnils will need to apply a slightly modified fix so one is able to run sd-redis with _2.7.2_ or _2.7.3_.  Currently we've several tests (unrelated to this issue) failing using _2.7.3_

**Comment by christophstrobl** [comment]
@marcosnils @HeartSaVioR @quaff created #149 to tackle upgarde issues. We now perform a safe lookup of either `ProtocolCommand` or `Protocol$Command` for usage with `Connection#sendCommand` which allows us to use 2.7.1, 2.7.2 and 2.7.3.

Concerning the test failures I found that 
```java
JedisPool pool = new JedisPool();

Jedis jedis = pool.getResource();
Transaction transaction = new Transaction(jedis.getClient());

jedis.multi();
transaction.set("foo".getBytes(), "bar".getBytes());
transaction.exec();

pool.returnResource(jedis);
```

Will cause `returnResource(jedis)` to fail with 
```
redis.clients.jedis.exceptions.JedisException: Could not return the resource to the pool
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR DISCARD without MULTI
```

Changing to `Transaction transaction = jedis.multi()` fixed it.

**Pull request closed without merging**
