### PR TITLE
DATAREDIS-971 Get correct signed BitFieldType.

### PR DESCRIPTION
**Pull request by dlmu-lq**
JIRA:https://jira.spring.io/browse/DATAREDIS-971

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAREDIS).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dlmu-lq Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=447)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=447) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dlmu-lq Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=447)!

**Comment by mp911de** [comment]
Please file an issue at https://jira.spring.io, descript the problem and please provide a test that backs the change.

**Comment by dlmu-lq** [comment]
@royclarkson this is a simple and careless mistake,the method in row 449 is as same as the method in row 459 before i modified it.

**Comment by dlmu-lq** [comment]
@mp911de this is a simple and careless mistake,the method in row 449 is as same as the method in row 459 before i modified it.

**Comment by mp911de** [comment]
The size of a change hasn't so much significance. It's important to document what's wrong, what we have to fix and providing tests that prove the change is correct.

**Comment by dlmu-lq** [comment]
@mp911de When I use the method in row 449 in the class org.springframework.data.redis.connection
BitFieldSubCommands.java, i need a signed BitFieldType,but i got an unsigned BitFieldType, isn't it serious enough?

**Comment by mp911de** [comment]
Check out our [Contribution Guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc) that describe what we do and why we do it. No need to convince us that your change is needed. We want to properly document what's going on. Since you already understood the issue, this makes you the right person to file a ticket with a proper description of the bug.

**Comment by mp911de** [comment]
Thanks a lot. That's merged and polished now. Please provide tests with future contributions that illustrate the actual problem.

**Comment by dlmu-lq** [comment]
@mp911de Thanks for your patience.

**Pull request closed without merging**
