### PR TITLE
Update CI.adoc to support JDK 17.

### PR DESCRIPTION
**Pull request by junghoon-vans**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

closes: #2766

### CODE REVIEW

**Comment by mp911de** [comment]
I think we would want to remove the CI docs as it doesn't add much benefit for our community. For ourselves, we have documented the requirements in `Jenkinsfile` and the actual versions are stored in `pipeline.properties`.

**Comment by junghoon-vans** [comment]
I think removing CI documentation completely makes it harder for community contributors to understand how to test locally.

**Comment by mp911de** [comment]
Good point. I was under the impression that the readme mentions `make` but it is only showing `mvn clean install`. Let me update the docs for that aspect.

**Comment by junghoon-vans** [comment]
Great, I see your fix.

**Pull request closed without merging**
