### PR TITLE
DATAREDIS-972 - Fix incorrect logic of validating command arguments

### PR DESCRIPTION
**Pull request by blackmonkey**
[DATAREDIS-972] Incorrect logic in RedisCommand.validateArgumentCount(int)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@blackmonkey Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=448)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=448) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@blackmonkey Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=448)!

**Comment by mp911de** [comment]
Thanks for your pull request. Care to provide a unit test backing the bugfix and that prevent future regressions?

**Comment by blackmonkey** [comment]
> Thanks for your pull request. Care to provide a unit test backing the bugfix and that prevent future regressions?

Has added several unit tests

**Comment by mp911de** [comment]
Thanks a lot. That's merged, polished and backported now. You might want to have a look at e0a059f96bd4f3e90bfb07e0bdf8a8e1981637b5 for things that we polished during the merge.

**Comment by blackmonkey** [comment]
@mp911de After finished my company's ticket, I was going to fix the failed tests and found you have done that. Thank you for helping!

**Pull request closed without merging**
