### PR TITLE
DATAREDIS-746 - zset union operation aggregation support

### PR DESCRIPTION
**Pull request by wongoo**
zset union operation aggregation support

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wongoo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=300)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=300) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@wongoo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=300)!

**Comment by mp911de** [comment]
Thanks a lot for submitting a pull request and sorry for the long radio silence. I'll take it from here.

**Comment by mp911de** [comment]
I picked up your changes which will be merged as part of #314.

**Pull request closed without merging**
