### PR TITLE
DATAREDIS-1054 - Add support for TypeReference in Jackson2JsonRedisSe…

### PR DESCRIPTION
**Pull request by fstonezst**
Hi，I'm Peter.
Jackson2JsonRedisSerializer is not support typeReference which jackson does. So I add support for typeReference in Jackson2JsonRedisSerializer. 

issue : https://jira.spring.io/browse/DATAREDIS-1054

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@fstonezst Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=487)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=487) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@fstonezst Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=487)!

**Comment by fstonezst** [comment]
@christophstrobl @jvalkeal @rmorgan @royclarkson  Is my description clear?  ：） @

**Comment by christophstrobl** [comment]
@fstonezst thanks for opening a PR and bringing this to our attention. We saw your request but haven't gotten to it yet. Please have a little patience. We'll update [DATAREDIS-1054](https://jira.spring.io/browse/DATAREDIS-1054) as soon as there's movement.

**Comment by fstonezst** [comment]
> @fstonezst thanks for opening a PR and bringing this to our attention. We saw your request but haven't gotten to it yet. Please have a little patience. We'll update [DATAREDIS-1054](https://jira.spring.io/browse/DATAREDIS-1054) as soon as there's movement.

**Comment by fstonezst** [comment]
@christophstrobl  U  can merge my pull request to  handle  DATAREDIS-1054 : )

**Pull request closed without merging**
