### PR TITLE
DATAREDIS-872 - InitialValue is not specified when two threads use the RedisAtomicInteger constructor concurrently, and two threads can cause thread safety issues.

### PR DESCRIPTION
**Pull request by programmeres**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAREDIS).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@programmeres Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=357)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=357) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by mp911de** [comment]
Please create a ticket in our [issue tracker](https://jira.spring.io/browse/DATAREDIS/) (as per our [contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc)) so we can understand, what exactly you want to achieve.

Please also note, adding a `public` method is not an obvious fix.

**Comment by pivotal-issuemaster** [comment]
@programmeres This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by pivotal-issuemaster** [comment]
@programmeres Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=357)!

**Comment by programmeres** [comment]
> Please create a ticket in our [issue tracker](https://jira.spring.io/browse/DATAREDIS/) (as per our [contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc)) so we can understand, what exactly you want to achieve.
> 
> Please also note, adding a `public` method is not an obvious issue fix.
>Where are the test cases written?

**Comment by programmeres** [comment]
> Please create a ticket in our [issue tracker](https://jira.spring.io/browse/DATAREDIS/) (as per our [contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc)) so we can understand, what exactly you want to achieve.
> 
> Please also note, adding a `public` method is not an obvious issue fix.



> Please create a ticket in our [issue tracker](https://jira.spring.io/browse/DATAREDIS/) (as per our [contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc)) so we can understand, what exactly you want to achieve.
> 
> Please also note, adding a `public` method is not an obvious issue fix.

 I've already createda ticket in our issue tracker, and then what?

**Pull request closed without merging**
