### PR TITLE
Add support for BitFieldSubCommands that generate multiple bit operations using non-chaining methods

### LINKED ISSUE #2055: Add support for BitFieldSubCommands that generate multiple bit operations using non-chaining methods
Currently `BitFieldSubCommands` supports redis `bitfiled` operations by chaining methods to generate multiple subcomamnd, as follows.

```java
    BitFieldSubCommands fieldSubCommands = BitFieldSubCommands.create()
            .get(BitFieldSubCommands.BitFieldType.unsigned(1)).valueAt(1)
            .get(BitFieldSubCommands.BitFieldType.unsigned(1)).valueAt(2);

    List<Long> result = redisTemplate.opsForValue().bitField("test", fieldSubCommands);
```

## Problem

However, the bitmap offset to be manipulated in the actual project is generated upstream by some rules, and it is not possible to directly use the above chain method to generate multiple bit fields for the operation of the command

```java

    // The offset data is usually obtained through the upstream method 
    // long[] offsetArray = getBitIndex();
    long[] offsetArray = new long[]{1,3,5,7,9};
    BitFieldSubCommands fieldSubCommands = BitFieldSubCommands.create();
    for (int i = 0; i < offsetArray.length; i++) {
            BitFieldSubCommands subCommands = BitFieldSubCommands.create.get(BitFieldSubCommands.BitFieldType.unsigned(1)).valueAt(offsetArray[i])；
            //There is no way to combine multiple commands
    }
   
    List<Long> result = redisTemplate.opsForValue().bitField("test",fieldSubCommands);

```

## Solution

In order to support such operations as mentioned above in my project, I modified the code related to `BitFieldSubCommands` by liberalizing the `BitFieldCommands` and `BitFieldCommand` implementation classes such as `BitFieldGet` constructor to be public, so that I can freely combine various bit operations in the following example way.

```java

    long[] offsetArray = new long[]{1,3,5,7,9};

    List<BitFieldSubCommands.BitFieldSubCommand> list = new ArrayList<>();

    for (int i = 0; i < offsetArray.length; i++) {
            BitFieldSubCommands.BitFieldGet bitFieldGet = new BitFieldSubCommands.BitFieldGet(BitFieldSubCommands.BitFieldType.unsigned(1),offsetArray[i]);

            list.add(bitFieldGet);
    }
    BitFieldSubCommands fieldSubCommands = new BitFieldSubCommands(list);
    List<Long> result = redisTemplate.opsForValue().bitField("test",fieldSubCommands);

```

See also [https://redis.io/commands/bitfield](https://redis.io/commands/bitfield) for further information.

### PR DESCRIPTION
**Pull request by Yanam**
resolves  #2055 

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Review by mp911de — CHANGES_REQUESTED** [review]
Instead of uncontrolled opening up the API, we should rather introduce factory methods with proper assertions, something like:

```java
BitFieldGet.create(…)
```

that can be later on used with `BitFieldSubCommands` through a `BitFieldSubCommands.create(BitFieldSubCommand…)` and `BitFieldSubCommands.create(Iterable<? extends BitFieldSubCommand>)`.

**Comment by Yanam** [comment]
> Instead of uncontrolled opening up the API, we should rather introduce factory methods with proper assertions, something like:
> 
> ```java
> BitFieldGet.create(…)
> ```
> 
> that can be later on used with `BitFieldSubCommands` through a `BitFieldSubCommands.create(BitFieldSubCommand…)` and `BitFieldSubCommands.create(Iterable<? extends BitFieldSubCommand>)`.

Thanks for the suggestion, I hadn't thought about it before, I'll submit a new pull later to improve it

**Comment by mp911de** [comment]
Feel free to either push additional commits onto your branch or force-push an amended commit. GitHub Pull requests automatically pick up your changes, so no need to create a new pull request.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and backported now.

**Pull request closed without merging**
