### PR TITLE
DATAREDIS-1191 - Return null if bucket empty

### PR DESCRIPTION
**Pull request by petergphillips**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@petergphillips Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=552)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=552) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@petergphillips Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=552)!

**Comment by mp911de** [comment]
Thanks for your pull request. As per comment in DATAREDIS-1191, `EntityReader.read(…)` should return a non-`null` therefore we need rather make sure that the `read(…)` method gets only called with non-empty buckets.

**Comment by mp911de** [comment]
That's fixed with c57b13c.

**Pull request closed without merging**
