### PR TITLE
DATAREDIS-444 - DefaultHashOperation does not return value

### PR DESCRIPTION
**Pull request by nsdiv**
DATAREDIS-444 - DefaultHashOperation does not return value

### CODE REVIEW

**Comment by nsdiv** [comment]
Changed HashOperations interface method delete to return Long, which is number of deleted elements. Modified DefaultHashOperations and HashOperationsTest

**Comment by mp911de** [comment]
Thanks for the PR. Would you (if you haven't done so yet) please sign the [Spring ICLA form](https://support.springsource.com/spring_committer_signup) and add your CLA number and name as a comment either here or to [DATAREDIS-444](https://jira.spring.io/browse/DATAREDIS-444).

**Comment by nsdiv** [comment]
Name - Ninad Divadkar, CLA # 169220160326121428

**Comment by mp911de** [comment]
Thanks, that's merged with bef4fbe8317205d7e2eb6f8442aef25d128cac7f.

**Pull request closed without merging**
