### PR TITLE
Add support for COPY via RedisOperations

### PR DESCRIPTION
**Pull request by ihaohong**
see #2040

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ihaohong Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=2059)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=2059) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ihaohong Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-redis&pullRequestId=2059)!

**Comment by ihaohong** [comment]
> Thanks for your contribution. I'm going to pick it up from here.

@mp911de  Hi, could you please tell me when my code would be picked?

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished now. I added reactive support for `COPY` as part of the [polishing commit](https://github.com/spring-projects/spring-data-redis/commit/7cd0669e86c291f3194d924613cede8b02ffb516). Sometimes merging a pull request takes a bit of time on our side as we can be busy with other things.

**Comment by ihaohong** [comment]
ok, thanks polishing 😊

**Pull request closed without merging**
